# wrangler.toml
name = 'test'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "eb06007e5a85460b94516a6d24f87b3c"				#KV数据库id
